name: PythonAnywhere Deployment

on:
  push:
    branches:
      - main  # Déclenche le déploiement lorsque vous poussez vers la branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to PythonAnywhere
      uses: chrispat/pythonanywhere-deploy-action@v1
      with:
        username: ${{ secrets.PYTHONANYWHERE_USERNAME }}
        password: ${{ secrets.PYTHONANYWHERE_PASSWORD }}
        domain: Mamadou93.pythonanywhere.com

    - name: Start Flask server
      run: |
        nohup python app.py &
